export default [
  {
    name: "Sincerity",
    description: "A battle rifle that fires a fast burst of three shots, each dealing moderate damage at medium range.",
    quote: "An all-around workhorse that radiates with primal power.",
    type: "Primary",
    title: "Battle Rifle",
    stats: [
      {
        level: 1,
        stats: [
          { name: "Health Max", value: "+15%" },
          { name: "Move Speed", value: "+5%" },
          { name: "Damage", value: "170" },
          { name: "Max Charges", value: "6" },
          { name: "Range", value: "9.8" },
          { name: "Volley Count", value: "3" },
          { name: "Primal Energy On Hit", value: "0.2%" },
          { name: "Reload Time", value: "1.8s" },
          { name: "Reactivation Delay", value: "0.3s" },
        ],
      },
    ],
    banner: "Support",
  },
  {
    name: "Boarson",
    description: "A shotgun with a slow rate of fire that shoots at close range in a moderate arc in front of you.",
    quote: "If hell doesn't exist, this will create it for you.",
    type: "Primary",
    title: "Shotgun",
    stats: [
      {
        level: 1,
        stats: [
          { name: "Health Max", value: "+40%" },
          { name: "Move Speed", value: "+7.5%" },
          { name: "Damage", value: "100" },
          { name: "Max Charges", value: "8" },
          { name: "Range", value: "5.4" },
          { name: "Arc per Volley", value: "30" },
          { name: "Shot Count", value: "5" },
          { name: "Primal Energy On Hit", value: "0.3%" },
          { name: "Reload Time", value: "2s" },
          { name: "Reactivation Delay", value: "0.3s" },
        ],
      },
    ],
    banner: "Vanguard",
  },
  {
    name: "Rush",
    description: "A rocket launcher that deals high damage to a small area at medium range.",
    quote: "Built by classicists with the intent to destroy primals.",
    type: "Primary",
    title: "Rocket Launcher",
    stats: [
      {
        level: 1,
        stats: [
          { name: "Health Max", value: "+17.5%" },
          { name: "Move Speed", value: "+0%" },
          { name: "Damage", value: "480" },
          { name: "Max Charges", value: "3" },
          { name: "Range", value: "9.8" },
          { name: "Detonate Radius", value: "2.1" },
          { name: "Primal Energy On Hit", value: "1%" },
          { name: "Reload Time", value: "1.8s" },
          { name: "Reactivation Delay", value: "0.4s" },
        ],
      },
    ],
    banner: "Primal Hunter",
  },
  {
    name: "Hailstrom!",
    description: "A mortar that lobs six explosive shots to single location, dealing high damage to a small area.",
    quote: "Could this thing be any more obnoxious?!",
    type: "Heavy",
    title: "Heavy Mortar",
    stats: [
      {
        level: 1,
        stats: [
          { name: "Damage", value: "400" },
          { name: "Max Charges", value: "2" },
          { name: "Range", value: "14" },
          { name: "Detonate Radius", value: "2.8" },
          { name: "Charge On Pickup", value: "100%" },
          { name: "Reactivation Delay", value: "0.4s" },
        ],
      },
    ],
    banner: "Primal Hunter",
  },
  {
    name: "Arrival",
    description: "A mortar that fires a single lobbed shot that explodes dealing very high damage to a large area.",
    quote: "Not a good first impression, but definitely a lasting one.",
    type: "Heavy",
    title: "Heavy Mortar",
    stats: [
      {
        level: 1,
        stats: [
          { name: "Damage", value: "880" },
          { name: "Max Charges", value: "2" },
          { name: "Range", value: "14" },
          { name: "Detonate Radius", value: "4.8" },
          { name: "Charge On Pickup", value: "75%" },
          { name: "Reactivation Delay", value: "0.4s" },
        ],
      },
      {
        level: 2,
        stats: [
          { name: "Damage", value: "897" },
          { name: "Max Charges", value: "2" },
          { name: "Range", value: "14" },
          { name: "Detonate Radius", value: "4.8" },
          { name: "Charge On Pickup", value: "75%" },
          { name: "Reactivation Delay", value: "0.4s" },
        ],
      },
    ],
    banner: "Primalist",
  },
  {
    name: "Primal Eye",
    description: "A sniper rifle with a slow rate of fire that shoots a single round for high damage at long range.",
    quote: "As if peering the fabric of the veil...",
    type: "Primary",
    title: "Sniper Rifle",
    stats: [
      {
        level: 1,
        stats: [
          { name: "Health Max", value: "+10%" },
          { name: "Move Speed", value: "+0%" },
          { name: "Damage", value: "540" },
          { name: "Max Charges", value: "5" },
          { name: "Range", value: "11.4" },
          { name: "Primal Energy On Hit", value: "1%" },
          { name: "Reload Time", value: "2s" },
          { name: "Reactivation Delay", value: "0.4s" },
        ],
      },
    ],
    banner: "Sniper",
  },
  {
    name: "Soft Thunder",
    description: "A mortar with a measured rate of fire that lobs a single round, dealing high damage to an area.",
    quote: "The rainstorms in the hills above Cardum have been known to resolve after a single clap of muted thunder.",
    type: "Primary",
    title: "Mortar",
    stats: [
      {
        level: 1,
        stats: [
          { name: "Health Max", value: "+12.5%" },
          { name: "Move Speed", value: "+3.75%" },
          { name: "Damage", value: "350" },
          { name: "Max Charges", value: "5" },
          { name: "Range", value: "9.8" },
          { name: "Detonate Radius", value: "2.4" },
          { name: "Primal Energy On Hit", value: ".2%" },
          { name: "Reload Time", value: "1.6s" },
          { name: "Reactivation Delay", value: "0.6s" },
        ],
      },
    ],
    banner: "Primal Hunter",
  },
  {
    name: "Objection",
    description: "A sniper rifle that fires a single shot for massive damage at very long range.",
    quote: `"This is the one." - Oren Lin, the assassination of Eryc`,
    type: "Heavy",
    title: "Heavy Sniper Rifle",
    stats: [
      {
        level: 1,
        stats: [
          { name: "Damage", value: "1350" },
          { name: "Max Charges", value: "3" },
          { name: "Range", value: "14" },
          { name: "Charge On Pickup", value: "120%" },
          { name: "Reactivation Delay", value: "1s" },
        ],
      },
      {
        level: 2,
        stats: [
          { name: "Damage", value: "1377" },
          { name: "Max Charges", value: "3" },
          { name: "Range", value: "14" },
          { name: "Charge On Pickup", value: "120%" },
          { name: "Reactivation Delay", value: "1s" },
        ],
      },
    ],
    banner: "Sniper",
  },
  {
    name: "The Heretic",
    description: "A rocket launcher that deals very high damage to a moderate area at very long range.",
    quote: `"Right now, going against 'tradition' means blowing it up."`,
    type: "Heavy",
    title: "Heavy Rocket Launcher",
    stats: [
      {
        level: 1,
        stats: [
          { name: "Damage", value: "940" },
          { name: "Max Charges", value: "2" },
          { name: "Range", value: "12" },
          { name: "Detonate Radius", value: "3.2" },
          { name: "Charge On Pickup", value: "80%" },
          { name: "Reactivation Delay", value: "0.4s" },
        ],
      },
      {
        level: 2,
        stats: [
          { name: "Damage", value: "958" },
          { name: "Max Charges", value: "2" },
          { name: "Range", value: "12" },
          { name: "Detonate Radius", value: "3.2" },
          { name: "Charge On Pickup", value: "80%" },
          { name: "Reactivation Delay", value: "0.4s" },
        ],
      },
    ],
    banner: "Seeker",
  },
  {
    name: "Splintered Fate",
    description:
      "A chaingun that deals moderate damage at medium range. Each subsequent shot increases attack speed while decreasing movement speed.",
    quote:
      "We will not give ground...even if Torden himself were to come wrest it from us! - Field Marshall Lander, the war for Eventide",
    type: "Primary",
    title: "Chaingun",
    stats: [
      {
        level: 1,
        stats: [
          { name: "Health Max", value: "+30%" },
          { name: "Move Speed", value: "+2.5%" },
          { name: "Damage", value: "104" },
          { name: "Max Charges", value: "42" },
          { name: "Range", value: "9.6" },
          { name: "Primal Energy On Hit", value: "0.09%" },
          { name: "Reload Time", value: "1.8s" },
          { name: "Reactivation Delay", value: "0.3s" },
        ],
      },
      {
        level: 2,
        stats: [
          { name: "Health Max", value: "+30%" },
          { name: "Move Speed", value: "+2.5%" },
          { name: "Damage", value: "106" },
          { name: "Max Charges", value: "42" },
          { name: "Range", value: "9.6" },
          { name: "Primal Energy On Hit", value: "0.09%" },
          { name: "Reload Time", value: "1.8s" },
          { name: "Reactivation Delay", value: "0.3s" },
        ],
      },
    ],
    banner: "Vanguard",
  },
  {
    name: "The Miser",
    description: "A flak cannon that deals high damage to a small area at medium range.",
    quote: "Protect what you treasure at the cost of your soul.",
    type: "Heavy",
    title: "Heavy Flak",
    stats: [
      {
        level: 1,
        stats: [
          { name: "Damage", value: "660" },
          { name: "Max Charges", value: "5" },
          { name: "Range", value: "7.4" },
          { name: "Detonate Radius", value: "2.2" },
          { name: "Charge On Pickup", value: "140%" },
          { name: "Reactivation Delay", value: "0.3s" },
        ],
      },
    ],
    banner: "Support",
  },
  {
    name: "Northern Warmth",
    description: "An assault rifle with a rapid rate of fire, moderate damage and medium range.",
    quote: 'The stoic denizens of the north are renowned for their "hospitality"',
    type: "Primary",
    title: "Assault Rifle",
    stats: [
      {
        level: 1,
        stats: [
          { name: "Health Max", value: "+15%" },
          { name: "Move Speed", value: "+6.25%" },
          { name: "Damage", value: "156" },
          { name: "Max Charges", value: "24" },
          { name: "Range", value: "8.6" },
          { name: "Primal Energy On Hit", value: "0.1%" },
          { name: "Reload Time", value: "1.6s" },
          { name: "Reactivation Delay", value: "0.1s" },
        ],
      },
      {
        level: 2,
        stats: [
          { name: "Health Max", value: "+15%" },
          { name: "Move Speed", value: "+6.25%" },
          { name: "Damage", value: "159" },
          { name: "Max Charges", value: "24" },
          { name: "Range", value: "8.6" },
          { name: "Primal Energy On Hit", value: "0.1%" },
          { name: "Reload Time", value: "1.6s" },
          { name: "Reactivation Delay", value: "0.1s" },
        ],
      },
    ],
    banner: "Seeker",
  },
  {
    name: "The Prodigal",
    description:
      "A sniper rifle with a slow rate of fire that shoots a single round for very high damage at long range.",
    quote: "For those that want everything up front--high likelihood of regret.",
    type: "Primary",
    title: "Sniper Rifle",
    stats: [
      {
        level: 1,
        stats: [
          { name: "Health Max", value: "+10%" },
          { name: "Move Speed", value: "+3.75%" },
          { name: "Damage", value: "720" },
          { name: "Max Charges", value: "3" },
          { name: "Range", value: "12.2" },
          { name: "Primal Energy On Hit", value: "2%" },
          { name: "Reload Time", value: "1.8s" },
          { name: "Reactivation Delay", value: "0.7s" },
        ],
      },
      {
        level: 2,
        stats: [
          { name: "Health Max", value: "+10%" },
          { name: "Move Speed", value: "+3.75%" },
          { name: "Damage", value: "734" },
          { name: "Max Charges", value: "3" },
          { name: "Range", value: "12.2" },
          { name: "Primal Energy On Hit", value: "2%" },
          { name: "Reload Time", value: "1.8s" },
          { name: "Reactivation Delay", value: "0.7s" },
        ],
      },
    ],
    banner: "Sniper",
  },
  {
    name: "Lost Dreamer",
    description: "An assault rifle with a rapid rate of fire, moderate damage and medium range.",
    quote: "A mask makes you question reality, but this will confirm the truth.",
    type: "Primary",
    title: "Assault Rifle",
    stats: [
      {
        level: 1,
        stats: [
          { name: "Health Max", value: "+25%" },
          { name: "Move Speed", value: "+5%" },
          { name: "Damage", value: "220" },
          { name: "Max Charges", value: "34" },
          { name: "Range", value: "9" },
          { name: "Primal Energy On Hit", value: "0.15%" },
          { name: "Reload Time", value: "1.4s" },
          { name: "Reactivation Delay", value: "0.2s" },
        ],
      },
      {
        level: 2,
        stats: [
          { name: "Health Max", value: "+25%" },
          { name: "Move Speed", value: "+5%" },
          { name: "Damage", value: "224" },
          { name: "Max Charges", value: "34" },
          { name: "Range", value: "9" },
          { name: "Primal Energy On Hit", value: "0.15%" },
          { name: "Reload Time", value: "1.4s" },
          { name: "Reactivation Delay", value: "0.2s" },
        ],
      },
    ],
    banner: "Primalist",
  },
  {
    name: "Facade",
    description: "A flak cannon that deals moderate to a small area at medium range.",
    quote: "Fantastic for building a wall...of explosions.",
    type: "Primary",
    title: "Flak",
    stats: [
      {
        level: 1,
        stats: [
          { name: "Health Max", value: "+22.5%" },
          { name: "Move Speed", value: "+5%" },
          { name: "Damage", value: "260" },
          { name: "Max Charges", value: "10" },
          { name: "Range", value: "7.6" },
          { name: "Detonate Radius", value: "2" },
          { name: "Primal Energy On Hit", value: "0.4%" },
          { name: "Reload Time", value: "2.2s" },
          { name: "Reactivation Delay", value: "0.3s" },
        ],
      },
      {
        level: 1,
        stats: [
          { name: "Health Max", value: "+22.5%" },
          { name: "Move Speed", value: "+5%" },
          { name: "Damage", value: "265" },
          { name: "Max Charges", value: "10" },
          { name: "Range", value: "7.6" },
          { name: "Detonate Radius", value: "2" },
          { name: "Primal Energy On Hit", value: "0.4%" },
          { name: "Reload Time", value: "2.2s" },
          { name: "Reactivation Delay", value: "0.3s" },
        ],
      },
    ],
    banner: "Protector",
  },
  {
    name: "Dispatch",
    description: "A battle rifle that fires a fast burst of three shots, each dealing moderate damage at long range.",
    quote: "The favored weapon of guerilla fighters from the Yurtac Accord.",
    type: "Heavy",
    title: "Heavy Battle Rifle",
    stats: [
      {
        level: 1,
        stats: [
          { name: "Damage", value: "270" },
          { name: "Max Charges", value: "5" },
          { name: "Range", value: "12.2" },
          { name: "Volley Count", value: "3" },
          { name: "Charge On Pickup", value: "20%" },
          { name: "Reactivation Delay", value: "0.3s" },
        ],
      },
      {
        level: 1,
        stats: [
          { name: "Damage", value: "275" },
          { name: "Max Charges", value: "5" },
          { name: "Range", value: "12.2" },
          { name: "Volley Count", value: "3" },
          { name: "Charge On Pickup", value: "20%" },
          { name: "Reactivation Delay", value: "0.3s" },
        ],
      },
    ],
    banner: "Ranger",
  },
  {
    name: "Trial",
    description: "A rocket launcher that deals high damage to a small area at long range.",
    quote: "Carried by Hafthor Vang during the second excursion to the Welkin isles.",
    type: "Primary",
    title: "Rocket Launcher",
    stats: [
      {
        level: 1,
        stats: [
          { name: "Health Max", value: "+15%" },
          { name: "Move Speed", value: "+2.5%" },
          { name: "Damage", value: "325" },
          { name: "Max Charges", value: "5" },
          { name: "Range", value: "10.4" },
          { name: "Detonate Radius", value: "2.6" },
          { name: "Primal Energy On Hit", value: "0.3%" },
          { name: "Reload Time", value: "2.4s" },
          { name: "Reactivation Delay", value: "0.3s" },
        ],
      },
      {
        level: 1,
        stats: [
          { name: "Health Max", value: "+15%" },
          { name: "Move Speed", value: "+2.5%" },
          { name: "Damage", value: "331" },
          { name: "Max Charges", value: "5" },
          { name: "Range", value: "10.4" },
          { name: "Detonate Radius", value: "2.6" },
          { name: "Primal Energy On Hit", value: "0.3%" },
          { name: "Reload Time", value: "2.4s" },
          { name: "Reactivation Delay", value: "0.3s" },
        ],
      },
    ],
    banner: "Primal Hunter",
  },
  {
    name: "Commotion",
    description: "A battle rifle that fires a fast burst of three shots, each dealing moderate damage at medium range.",
    quote: `"You'll all get shot...whether it's your fault or not" - Rylan Hamerain, in defense of Lower Wilds`,
    type: "Primary",
    title: "Battle Rifle",
    stats: [
      {
        level: 1,
        stats: [
          { name: "Health Max", value: "+22.5%" },
          { name: "Move Speed", value: "+6.25%" },
          { name: "Damage", value: "220" },
          { name: "Max Charges", value: "9" },
          { name: "Range", value: "9.4" },
          { name: "Volley Count", value: "3" },
          { name: "Primal Energy On Hit", value: "0.15%" },
          { name: "Reload Time", value: "1.4s" },
          { name: "Reactivation Delay", value: "0.4s" },
        ],
      },
      {
        level: 2,
        stats: [
          { name: "Health Max", value: "+22.5%" },
          { name: "Move Speed", value: "+6.25%" },
          { name: "Damage", value: "224" },
          { name: "Max Charges", value: "9" },
          { name: "Range", value: "9.4" },
          { name: "Volley Count", value: "3" },
          { name: "Primal Energy On Hit", value: "0.15%" },
          { name: "Reload Time", value: "1.4s" },
          { name: "Reactivation Delay", value: "0.4s" },
        ],
      },
    ],
    banner: "Ranger",
  },
  {
    name: "The Caretaker",
    description: "A shotgun with a slow rate of fire that shoots at short range in a moderate arc in front of you.",
    quote: `To do great work is to love what you do.`,
    type: "Primary",
    title: "Shotgun",
    stats: [
      {
        level: 1,
        stats: [
          { name: "Health Max", value: "+30%" },
          { name: "Move Speed", value: "+10%" },
          { name: "Damage", value: "90" },
          { name: "Max Charges", value: "5" },
          { name: "Range", value: "6.2" },
          { name: "Arc per Volley", value: "25" },
          { name: "Shot Count", value: "7" },
          { name: "Primal Energy On Hit", value: "0.12%" },
          { name: "Reload Time", value: "1.8s" },
          { name: "Reactivation Delay", value: "0.4s" },
        ],
      },
      {
        level: 2,
        stats: [
          { name: "Health Max", value: "+30%" },
          { name: "Move Speed", value: "+10%" },
          { name: "Damage", value: "91" },
          { name: "Max Charges", value: "5" },
          { name: "Range", value: "6.2" },
          { name: "Arc per Volley", value: "25" },
          { name: "Shot Count", value: "7" },
          { name: "Primal Energy On Hit", value: "0.12%" },
          { name: "Reload Time", value: "1.8s" },
          { name: "Reactivation Delay", value: "0.4s" },
        ],
      },
    ],
    banner: "Vanguard",
  },
  {
    name: "Luma Prodigal",
    description:
      "A powerful long range sniper that deals more damage and travels even further than its non-Ancient counterpart, but has only 2 shots in the magazine.",
    quote:
      "Crafted using the same techniques employed by the SacredForm to embue their masks, thi variant packs more power into a single round than it's traditional form.",
    type: "Primary",
    title: "Sniper Rifle",
    stats: [
      {
        level: 1,
        stats: [
          { name: "Health Max", value: "-10%" },
          { name: "Move Speed", value: "+2.5%" },
          { name: "Damage", value: "880" },
          { name: "Max Charges", value: "2" },
          { name: "Range", value: "12.8" },
          { name: "Primal Energy On Hit", value: "0.8%" },
          { name: "Reload Time", value: "2s" },
          { name: "Reactivation Delay", value: "0.7s" },
        ],
      },
      {
        level: 2,
        stats: [
          { name: "Health Max", value: "-10%" },
          { name: "Move Speed", value: "+2.5%" },
          { name: "Damage", value: "897" },
          { name: "Max Charges", value: "2" },
          { name: "Range", value: "12.8" },
          { name: "Primal Energy On Hit", value: "0.8%" },
          { name: "Reload Time", value: "2s" },
          { name: "Reactivation Delay", value: "0.7s" },
        ],
      },
    ],
    banner: "Sniper",
  },
  {
    name: "Avalanche",
    description:
      "A mortar that fires six lobbed shots in rapid succession, each detonating a short distance from the previous.",
    quote: "You won't realize you've lost ground until it's too late.",
    type: "Heavy",
    title: "Heavy Mortar",
    stats: [
      {
        level: 1,
        stats: [
          { name: "Damage", value: "650" },
          { name: "Max Charges", value: "2" },
          { name: "Range", value: "15" },
          { name: "Detonate Radius", value: "2.25" },
          { name: "Charge On Pickup", value: "150%" },
          { name: "Reactivation Delay", value: "0.4s" },
        ],
      },
      {
        level: 1,
        stats: [
          { name: "Damage", value: "663" },
          { name: "Max Charges", value: "2" },
          { name: "Range", value: "15" },
          { name: "Detonate Radius", value: "2.25" },
          { name: "Charge On Pickup", value: "150%" },
          { name: "Reactivation Delay", value: "0.4s" },
        ],
      },
    ],
    banner: "Primal Hunter",
  },
  {
    name: "Renegade",
    description: "An assault rifle with a rapid rate of fire that deals high damage at long range.",
    quote: "A weapon so anxious to fire, picking it up is a risk most opt to avoid.",
    type: "Heavy",
    title: "Heavy Assault Rifle",
    stats: [
      {
        level: 1,
        stats: [
          { name: "Damage", value: "420" },
          { name: "Max Charges", value: "9" },
          { name: "Range", value: "9" },
          { name: "Charge On Pickup", value: "+314%" },
          { name: "Reactivation Delay", value: "0.1s" },
        ],
      },
      {
        level: 2,
        stats: [
          { name: "Damage", value: "428" },
          { name: "Max Charges", value: "9" },
          { name: "Range", value: "9" },
          { name: "Charge On Pickup", value: "+314%" },
          { name: "Reactivation Delay", value: "0.1s" },
        ],
      },
    ],
    banner: "Assassin",
  },
  {
    name: "Findlay",
    description:
      "A chaingun that deals high damage at long range. Each subsequent shot increases attack speed while decreasing movement speed.",
    quote: "An icon. Hold the lever down until it stops. Reload. Then, do it again.",
    type: "Heavy",
    title: "Heavy Assault Rifle",
    stats: [
      {
        level: 1,
        stats: [
          { name: "Damage", value: "270" },
          { name: "Max Charges", value: "32" },
          { name: "Range", value: "11.6" },
          { name: "Charge On Pickup", value: "+325%" },
          { name: "Reactivation Delay", value: "0.4s" },
        ],
      },
      {
        level: 2,
        stats: [
          { name: "Damage", value: "275" },
          { name: "Max Charges", value: "32" },
          { name: "Range", value: "11.6" },
          { name: "Charge On Pickup", value: "+325%" },
          { name: "Reactivation Delay", value: "0.4s" },
        ],
      },
    ],
    banner: "Vanguard",
  },
  {
    name: "Luma Arrival",
    description: "",
    quote:
      "Acolytes of the Sacred Form specialized in drawing heightened power out of catalyst. As a result, this weapon carries a single charge, but can discharge more power than the standard counterpart.",
    type: "Heavy",
    title: "Heavy Mortar",
    stats: [
      {
        level: 1,
        stats: [
          { name: "Damage", value: "1250" },
          { name: "Max Charges", value: "1" },
          { name: "Range", value: "16" },
          { name: "Detonate Radius", value: "5.8" },
          { name: "Charge On Pickup", value: "+65%" },
          { name: "Reactivation Delay", value: "0.4s" },
        ],
      },
      {
        level: 2,
        stats: [
          { name: "Damage", value: "1275" },
          { name: "Max Charges", value: "1" },
          { name: "Range", value: "16" },
          { name: "Detonate Radius", value: "5.8" },
          { name: "Charge On Pickup", value: "+65%" },
          { name: "Reactivation Delay", value: "0.4s" },
        ],
      },
    ],
    banner: "Primal Hunter",
  },
]
